# This workflow will build a package using Gradle

name: Gradle Build

on:
  push:
    branches: ['*']
  pull_request:
    types: [opened, synchronize]
#  release:
#    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Download repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle build test

# ... and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle
#
#    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
#    # the publishing section of your build.gradle
#    - name: Publish to GitHub Packages
#      run: gradle publish
#      env:
#        USERNAME: ${{ github.actor }}
#        TOKEN: ${{ secrets.GITHUB_TOKEN }}
